### ISSUE TITLE
Añadir enlace en eventos para Google Calendar

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycan-web#361]
Sería interesante incorporar un enlace para añadir el evento a Google Calendar con lo que se podría conseguir una mayor fidelización de posibles asistentes.

Generador de enlaces: https://decomaan.github.io/google-calendar-link-generator/

**Comment by CrisKrus** [comment]
He estado mirando esta issue y entiendo que solamente tiene sentido tener esta opción en los eventos futuros. ¿Estoy en lo cierto? Ya que en los eventos que ya han pasado no vale de nada añadirlo al calendario

**Comment by CrisKrus** [comment]
Perfecto, miro si puedo poner algo en la parte de eventos futuros. Lo que no se si hacerlo con un botón o un texto con un enlace 🤔

**Comment by sdelquin** [comment]
Hola @CrisKrus. Has podido mirar algo de esto?

**Comment by CrisKrus** [comment]
He estado haciendo una primera versión pero tengo una duda (con las templates de Django). El formato esperado del enlace es el siguiente: 

```
https://www.google.com/calendar/render?action=TEMPLATE&text=MyEventName&details=MyDescription&location=MyLoxation&dates=20211022T164500Z%2F20211021T164200Z
```

Pero a la hora de generar la última parte del enlace dónde va la fecha y hora de finalización no se como hacer el cálculo partiendo de la fecha y hora de inicio y el tiempo estimado de duración.

```
https://www.google.com/calendar/render?action=TEMPLATE&text={{ event.name }}&details={{ event.description }}&location={{ event.venue }}&dates={{ event.start_datetime | date:'Ymd\Thm00\Z' }}%2Fundefined
```

De momento tengo puesto undefined por eso. 

Ahora mientras escribo esta duda he pensado que igual tiene sentido crear un método en el modelo que haga el cálculo y me devuelva la fecha directamente :thinking:
