### ISSUE TITLE
Citas aleatorias en página de inicio

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/pycan-web#378]
El objetivo sería que la cita que actualmente se muestra en la página de inicio fuera cambiando de manera dinámica sin necesidad de recargar la página.

Para poder implementar esta tarea queda pendiente que la [API actual](https://github.com/pythoncanarias/pycan-web/tree/main/apps/api) devuelva las citas.

**Comment by navascogt** [comment]
@sdelquin Ya de regreso luego de revisar y comprender de Django, voy a revisar y tomar este issue.

**Comment by sdelquin** [comment]
Sí claro. La idea era con Javascript 👍🏻
