### ISSUE TITLE
mejoras en el diseño de la web

### ISSUE THREAD

**Issue by AmandaKhol** [pythoncanarias/pycan-web#424]
El objetivo de esta issue es realizar cambios en el diseño de la web en cuanto a:

- gama cromática
- limpieza de archivos de layout
- armonía en el color de enlaces y botones
- armonía en márgenes

**Comment by sdelquin** [comment]
Hola @AmandaKhol. Qué hacemos con la issue?

**Comment by sdelquin** [comment]
Si te parece, paso a cerrar esta issue que intentaremos ir desglosando en nuevas issues más pequeñas y concretas.

**Comment by AmandaKhol** [comment]
perfecto!
